In [2]:
import sys
from pathlib import Path

# Force notebook to recognize project root
import os
ROOT = Path(os.getcwd()).resolve().parents[0] # one level up from tests/
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

import pandas as pd
from src.inference_pipeline.inference import predict

# Load a few rows of already preprocessed data
sample_path = ROOT / "data/processed/cleaning_dev.csv"
df = pd.read_csv(sample_path).sample(5, random_state=42).reset_index(drop=True)

print("Input sample:")
display(df.head())

# Run inference
preds_df = predict(df)
print("✅ Predictions returned")
display(preds_df[["predicted_price"]].head())

Input sample:

,Unnamed: 0,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,...,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng
0,83736,2021-02-28,440000.0,399945.0,158.775074,176.508385,52.0,43.0,64.0,13.0,...,397400.0,6617.0,501.0,9991.0,9991.0,5263.0,467239.719505,Washington-Arlington-Alexandria,38.8446,-77.5092
1,40282,2020-07-31,240000.0,249900.0,160.666667,166.600000,9.0,6.0,5.0,3.0,...,281550.0,0.0,0.0,0.0,0.0,0.0,250425.875854,Philadelphia-Camden-Wilmington,39.9056,-75.3020
2,144068,2021-12-31,281000.0,305000.0,165.030675,182.525160,49.0,52.0,47.0,33.0,...,193900.0,7646.0,375.0,14580.0,14580.0,6658.0,293367.136566,Houston-Pasadena-The Woodlands,29.8422,-95.3855
3,91031,2021-03-31,253990.0,259900.0,135.362015,138.504155,333.0,382.0,369.0,54.0,...,213100.0,30927.0,1361.0,51553.0,51553.0,26711.0,248121.129880,Tampa-St. Petersburg-Clearwater,28.1538,-82.4050
4,138468,2021-11-30,412000.0,400000.0,251.294818,255.534072,178.0,177.0,146.0,86.0,...,0.0,0.0,0.0,0.0,0.0,0.0,436291.086415,New York-Newark-Jersey City,40.7222,-74.0225

Skipping lat/lng merge: already present in DataFrame.
✅ Dropped 0 duplicate rows (excluding date/year).
✅ Removed 0 rows with median_list_price > 19M.
✅ Predictions returned

   predicted_price
0     510414.31250
1     357581.87500
2     398950.65625
3     333710.65625
4     528746.50000